#ifndef WEB_UI_H
#define WEB_UI_H

static const char WEB_UI_HTML[] =
"<!DOCTYPE html>"
"<html><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Little Red Raccoon MUD</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"html,body{width:100%;height:100%;background:#000;color:#0f0;font-family:'Courier New',Courier,monospace;font-size:14px;line-height:1.3;overflow:hidden}"
"#login-screen{display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;padding:20px}"
"#login-screen .title{color:#0f0;font-size:16px;font-weight:bold;text-align:center;margin-bottom:20px;white-space:pre}"
"#login-screen .subtitle{color:#0a0;margin-bottom:30px}"
"#login-form{display:flex;flex-direction:column;align-items:center;gap:10px}"
"#login-form label{color:#0f0;font-size:14px}"
"#login-form input{background:#111;color:#0f0;border:1px solid #0f0;padding:8px 12px;font-family:inherit;font-size:14px;width:200px;text-align:center;outline:none}"
"#login-form input:focus{border-color:#0f0;box-shadow:0 0 8px rgba(0,255,0,.3)}"
"#login-form button{background:#0f0;color:#000;border:none;padding:8px 24px;font-family:inherit;font-size:14px;font-weight:bold;cursor:pointer}"
"#login-form button:hover{background:#0c0}"
"#login-error{color:#f00;margin-top:10px;display:none}"
"#game-screen{display:none;flex-direction:column;height:100%}"
"#output{flex:1;overflow-y:auto;padding:10px;white-space:pre-wrap;word-wrap:break-word;scroll-behavior:smooth}"
"#output::-webkit-scrollbar{width:8px}"
"#output::-webkit-scrollbar-track{background:#111}"
"#output::-webkit-scrollbar-thumb{background:#0f0;border-radius:4px}"
"#input-line{display:flex;align-items:center;padding:8px 10px;border-top:1px solid #0f0;background:#050505}"
"#input-line .prompt{color:#0f0;margin-right:8px;flex-shrink:0}"
"#command-input{flex:1;background:transparent;color:#0f0;border:none;outline:none;font-family:inherit;font-size:14px;caret-color:#0f0}"
"#command-input::placeholder{color:#060}"
".highlight-yellow{color:#ff0}"
".highlight-cyan{color:#0ff}"
".highlight-magenta{color:#f0f}"
".highlight-green{color:#0f0}"
".highlight-red{color:#f00}"
".highlight-bold{font-weight:bold}"
"@media(max-width:600px){html,body{font-size:12px}#login-screen .title{font-size:10px}}"
"</style>"
"</head><body>"
"<div id='login-screen'>"
"<div class='title'>"
"  | |    (*) | | | | |  \n"
"  | |     *| |*| |*| | ___ \n"
"  | |    | | __| __| |/ _ \\\n"
"  | |__**| | |*| |*| |  __/\n"
"  |******|*|_*|_*|*|_||   \n"
"\n"
"   RED RACCOON MUD\n"
"</div>"
"<div class='subtitle'>A Multi-User Dungeon for Trash Pandas</div>"
"<div id='login-form'>"
"<label for='name-input'>Enter your name:</label>"
"<input id='name-input' type='text' maxlength='15' placeholder='Raccoon Name' autofocus>"
"<button id='login-btn'>Enter the Forest</button>"
"</div>"
"<div id='login-error'></div>"
"</div>"
"<div id='game-screen'>"
"<div id='output'></div>"
"<div id='input-line'>"
"<span class='prompt'>&gt;</span>"
"<input id='command-input' type='text' placeholder='Type a command...' autocomplete='off' spellcheck='false'>"
"</div>"
"</div>"
"<script>"
"(function(){"
"var token=localStorage.getItem('mud_token')||'';"
"var loginScreen=document.getElementById('login-screen');"
"var gameScreen=document.getElementById('game-screen');"
"var output=document.getElementById('output');"
"var cmdInput=document.getElementById('command-input');"
"var nameInput=document.getElementById('name-input');"
"var loginBtn=document.getElementById('login-btn');"
"var loginError=document.getElementById('login-error');"
"var eventSource=null;"
"var reconnectTimer=null;"
""
"function urlencode(s){return encodeURIComponent(s).replace(/%20/g,'+')}"
""
"function stripAnsi(s){return s.replace(/\\x1B\\[[0-9;]*[a-zA-Z]/g,'').replace(/\\r/g,'')}"
""
"function appendOutput(text){"
"if(!text)return;"
"text=stripAnsi(text);"
"var lines=text.split('\\n');"
"for(var i=0;i<lines.length;i++){"
"var line=lines[i];"
"var div=document.createElement('div');"
"div.textContent=line;"
"output.appendChild(div);"
"}"
"output.scrollTop=output.scrollHeight;"
"}"
""
"function showGame(){"
"loginScreen.style.display='none';"
"gameScreen.style.display='flex';"
"cmdInput.focus();"
"}"
""
"function connectSSE(tok){"
"if(eventSource){eventSource.close()}"
"eventSource=new EventSource('/api/events?token='+encodeURIComponent(tok));"
"eventSource.onmessage=function(e){"
"if(e.data&&e.data!=='keepalive'){"
"appendOutput(e.data.replace(/\\r/g,''));"
"}"
"};"
"eventSource.onerror=function(){"
"eventSource.close();"
"reconnectTimer=setTimeout(function(){connectSSE(tok)},3000);"
"};"
"}"
""
"function doLogin(name){"
"var xhr=new XMLHttpRequest();"
"xhr.open('POST','/api/login',true);"
"xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded');"
"xhr.onload=function(){"
"if(xhr.status===200){"
"var resp=JSON.parse(xhr.responseText);"
"token=resp.token;"
"localStorage.setItem('mud_token',token);"
"loginScreen.style.display='none';"
"gameScreen.style.display='flex';"
"if(resp.motd) appendOutput(resp.motd);"
"connectSSE(token);"
"cmdInput.focus();"
"}else{"
"var msg='Login failed';"
"try{var e=JSON.parse(xhr.responseText);if(e.error==='name_taken')msg='That name is already taken.';else if(e.error==='invalid_name')msg='Invalid name. Use letters, numbers, and underscores only (1-15 chars).';else if(e.error==='server_full')msg='The forest is full. Try again later.'}catch(ex){}"
"loginError.textContent=msg;"
"loginError.style.display='block';"
"nameInput.focus();"
"}"
"};"
"xhr.onerror=function(){loginError.textContent='Connection error';loginError.style.display='block'};"
"xhr.send('name='+urlencode(name));"
"}"
""
"function sendCommand(cmd){"
"if(!token||!cmd.trim())return;"
"appendOutput('> '+cmd);"
"var xhr=new XMLHttpRequest();"
"xhr.open('POST','/api/command',true);"
"xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded');"
"xhr.onload=function(){"
"if(xhr.status===200){"
"try{var resp=JSON.parse(xhr.responseText);if(resp.status==='quit'){"
"localStorage.removeItem('mud_token');"
"setTimeout(function(){window.location.reload()},1000);"
"}}catch(ex){}"
"}else if(xhr.status===401){"
"appendOutput('\\nSession expired. Please refresh.');"
"}"
"};"
"xhr.send('token='+encodeURIComponent(token)+'&command='+urlencode(cmd));"
"}"
""
"loginBtn.addEventListener('click',function(){"
"var name=nameInput.value.trim();"
"if(!name){loginError.textContent='Please enter a name';loginError.style.display='block';return}"
"loginError.style.display='none';"
"doLogin(name);"
"});"
""
"nameInput.addEventListener('keydown',function(e){"
"if(e.key==='Enter'){e.preventDefault();loginBtn.click()}"
"});"
""
"cmdInput.addEventListener('keydown',function(e){"
"if(e.key==='Enter'){"
"var cmd=cmdInput.value.trim();"
"cmdInput.value='';"
"if(cmd) sendCommand(cmd);"
"}"
"});"
""
"if(token){"
"var es=new EventSource('/api/events?token='+encodeURIComponent(token));"
"var reconnectOk=false;"
"es.onmessage=function(e){"
"if(!reconnectOk){reconnectOk=true;showGame();}"
"if(e.data&&e.data!=='keepalive'){"
"appendOutput(e.data.replace(/\\r/g,''));"
"}"
"};"
"es.onerror=function(){"
"if(!reconnectOk){"
"es.close();"
"localStorage.removeItem('mud_token');"
"}else{"
"es.close();"
"reconnectTimer=setTimeout(function(){connectSSE(token)},3000);"
"}"
"};"
"eventSource=es;"
"}"
"})();"
"</script>"
"</body></html>";

#endif
